# Generated by Django 5.2.14 on 2026-05-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=80)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['survey_number'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=120)),
                ('taluka', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_crop', models.CharField(choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('sugarcane', 'Sugarcane'), ('cotton', 'Cotton'), ('soybean', 'Soybean'), ('jowar', 'Jowar')], max_length=20)),
                ('photo', models.ImageField(upload_to='crop_submissions/')),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_crop', models.CharField(blank=True, choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('sugarcane', 'Sugarcane'), ('cotton', 'Cotton'), ('soybean', 'Soybean'), ('jowar', 'Jowar')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_fraud', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='krishinetra_api.farm')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='krishinetra_api.farmer'),
        ),
        migrations.AlterUniqueTogether(
            name='farm',
            unique_together={('farmer', 'survey_number')},
        ),
    ]
